import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/blocks/Header";
import Footer from "@/components/blocks/Footer";

export const metadata: Metadata = {
    title: "Magic Knotes",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className="antialiased"
            >
                <Header />
                {children}
                <Footer />
            </body>
        </html>
    );
}
