import type { Metadata } from "next";
import "./globals.css";
import Footer from "@/components/blocks/Footer";
import { Urbanist } from 'next/font/google'

const urbanist = Urbanist({
    subsets: ['latin'],
})

export const metadata: Metadata = {
    title: "Magic Knotes",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`${urbanist.className} antialiased`}
            >
                {children}
                <Footer />
            </body>
        </html>
    );
}
